games_plus/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('games_review.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

games_review/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from games_review import views

app_name = 'games_review'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^jeu/(?P<slug>[\w-]+)/$', views.game, name='game'),
    url('^', include('django.contrib.auth.urls'))
]

games_review/models.py
# encoding:utf-8
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User


# Game types
class Type(models.Model):
    name = models.CharField(max_length=150)
    slug = models.SlugField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Categorie'
        verbose_name_plural = 'Categories'


class Game(models.Model):
    name = models.CharField(max_length=150, verbose_name="Nom")
    slug = models.SlugField()
    author = models.ForeignKey(User, verbose_name="Auteur")
    release_date = models.DateTimeField(auto_now_add=True)
    picture = models.ImageField(help_text="Pour garentir une experience utilisateur optimale, n'utilisez que des "
                                          "images .png")
    types = models.ManyToManyField(Type)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Jeu'
        verbose_name_plural = 'Jeux'


class Comment(models.Model):
    author = models.ForeignKey(User, related_name="comments")
    body = models.TextField(max_length=300)
    game = models.ForeignKey(Game, related_name="comments")
    date = models.DateField(auto_now=True, verbose_name="Date")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Commentaire'
        verbose_name_plural = 'Commentaires'

games_review/forms.py
from django import forms
from models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']
        widgets = {
            'body': forms.Textarea(attrs={'class': 'form-control'})
        }

games_review/views.py
from django.shortcuts import render, get_object_or_404, redirect
from games_review.models import *
from django.core.paginator import *
from forms import CommentForm


# root page of the web site. Establishes a paginated list of games and displays their links. Search field to filter
# by name
def index(request):
    # Check if requests have been made
    if request.GET.get('search_games'):
        game_list = Game.objects.filter(name__icontains=request.GET.get('search_games'))
    elif request.GET.get('type'):
        type = get_object_or_404(Type, slug=request.GET.get('type'))
        game_list = Game.objects.filter(types=type)
    else:
        game_list = Game.objects.all()

    paginator = Paginator(game_list, 9)

    page = request.GET.get('page')
    try:
        games = paginator.page(page)
    except PageNotAnInteger:
        games = paginator.page(1)
    except EmptyPage:
        games = paginator.page(paginator.num_pages)

    return render(request, 'index.html', {'games': games, 'INDEX_PAGE_TITLE': 'Liste des jeux'})


# Game description in wich you can post comments if authenticated. Game types are links back to index with type
# filter parameter
def game(request, slug):
    game = get_object_or_404(Game, slug=slug)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(False)
            comment.game = game
            comment.author = request.user
            comment.save()
    else:
        form = CommentForm()

    comments = game.comments.all()
    return render(request, 'game.html', {'game': game, 'comments': comments, 'form': form})


def logout(request):
    logout(request)
    return redirect('/login', permanent=True)

games_review/templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>{% block title %}Games plus{% endblock %}</title>
    <link href="{% static "css/styles.css" %}" rel="stylesheet"/>
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet"/>
    <link href="{% static "css/font-awesome.min.css" %}" rel="stylesheet"/>
    <script src="{% static "js/jquery-3.2.1.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
</head>
    <body>
        <header style="background: url('{% static 'img/header.jpg' %}')" class="jumbotron">
            <div class="header-title-zone container page-header">
                <h1>Super Games Review</h1>
                <hr/>
                <h2>With an awesome generic header</h2>
            </div>
        </header>
        <div class="container">
        <div class="subpage-header">
            <h2>{% block page_title %} {% endblock %}</h2>
            {% if user.is_authenticated %}
                <p>Bienvenue, {{ user.username }}. Tu peux commenter des jeux !
                    Ce n'est pas vous ? <a href="{% url 'games_review:logout' %}?next=/login">Se déconnecter</a>
                </p>
            {% else %}
                <p>Salutations, nouveau voyageur. Si tu veux pouvoir commenter des jeux, <a href="/login">connecte toi</a></p>
            {% endif %}
        </div>
        {% block body %}{% endblock %}
        </div>
        <footer>
            <div class="social-links">
                <a href="https://github.com/singeryo/games_plus" target="_blank"><i class="fa fa-github footer-icon"></i></a>
                <a href="#"><i class="fa fa-facebook-official footer-icon"></i></a>
                <a href="#"><i class="fa fa-twitter-square footer-icon"></i></a>
            </div>
        </footer>
    </body>
<script src="{% static "js/games_review.js" %}"></script>
</html>

games_review/templates/game.html
{% extends "_base.html" %}
{% block title %}{{ game }}{% endblock %}
{% block page_title %}{{ game }}{% endblock %}
{% block body %}
    <ol class="breadcrumb">
      <li><a href="/">Home</a></li>
      <li class="active">{{ game }}</li>
    </ol>
    <div class="game-page-banner col-md-12"><img src="{{ game.picture.url }}" class="img-responsive"/></div>
    <div class=game-info>
        <table class="table table-bordered table-responsive table-hover">
            <tr>
                <td>Nom</td>
                <td>{{ game }}</td>
            </tr>
            <tr>
                <td>Date de sortie</td>
                <td>{{ game.release_date }}</td>
            </tr>
            <tr>
                <td>Types</td>
                <td>
                    <ul>
                        {% for type in game.types.all %}
                            <li><a href="/?type={{ type.slug }}">{{ type.name }}</a></li>
                        {% endfor %}
                    </ul>
                </td>
            </tr>
        </table>
    </div>
    <div class="comment-section">
        <div class="existing-comments">
            <h3>Commentaires</h3>
            {% for comment in comments %}
                <div class="comment panel panel-default">
                    <div class="panel-heading">
                        <span class="panel-title">Ecrit par {{ comment.author }}</span>
                        <span> -- {{ comment.date | date }}</span>
                    </div>
                    <div class="panel-body">
                    <p>{{ comment.body }}</p>

                    </div>
                </div>
            {% endfor %}
        </div>
        {% if user.is_authenticated %}
            <form method="post" action="{% url 'games_review:game' game.slug %}">
                {% csrf_token %}
                <div class="new-comment form-group">
                    <label>Nouveau commentaire</label>
                    {{ form.body }}
                </div>
                <div class="form-group col-md-2">
                    <button class="btn-success form-control" type="submit">Poster</button>
                </div>
            </form>
        {% else %}
            <p>Pour écrir un commentaire, veuillez vous <a href="/login">connecter</a></p>
        {% endif %}
    </div>

{% endblock %}

games_review/templates/index.html
{% extends "_base.html" %}
{% block title %}{{ INDEX_PAGE_TITLE }}{% endblock %}
{% block page_title %}{{ INDEX_PAGE_TITLE }}{% endblock %}
{% block body %}
    <div class="list-desc">
        <p>Voici la liste de mes jeux tu peux cliquer dessus pour voir la revue</p>
        <form method="get" action=".">
            <input class="search-input" type="text" name="search_games" placeholder="La tu peux chercher des jeux c'est cool ..."/>
            <button type="submit">Rechercher</button>
        </form>
    </div>
    <div class="container">
        <ul class="col-md-12">
            {% for game in games %}
                <li class="game-item col-md-3">
                    <div class="row">
                        <a href="{% url 'games_review:game' game.slug %}">
                            <div class="game-label col-md-12">{{ game.name }}</div>
                            <div class="col-md-12 img-container" style="display: none"><img src="{{ game.picture.url }}" class="img-responsive"/></div>
                        </a>
                    </div>
                </li>
            {% empty %}
                <p>Aucun jeu ne correspond à votre recherche</p>
            {% endfor %}
        </ul>
    </div>
    <div class="pagination">
        <nav aria-label="Page navigation">
          <ul class="pagination">
            <li>
              {% if games.has_previous %}
                    <a href="?page={{ games.paginator.page_range.0 }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                {% endif %}
            </li>
            {% for page in games.paginator.page_range %}
                <li {% if page == games.number %} class="active" {% endif %}><a href="?page={{ page }}">{{ page }}</a></li>
            {% endfor %}
            <li>
                {% if games.has_next %}
                    <a href="?page={{ games.paginator.num_pages }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                {% endif %}
            </li>
          </ul>
        </nav>
    </div>
{% endblock %}